alias rm="rm -i"
alias ls="ls -GAF"
alias la="ls -l"
alias utf8='find . -type f | xargs -n 10 nkf --overwrite'

alias uproxy='export http_proxy="http://proxy.uec.ac.jp:8080"; export https_proxy="http://proxy.uec.ac.jp:8080"'
alias nuproxy='export http_proxy=""; export https_proxy=""'

alias mig_dev='bundle exec rake db:drop db:schema:load db:seed RAILS_ENV=development'
alias mig_test='bundle exec rake db:drop db:migrate db:seed RAILS_ENV=test'

#重複履歴を無視
export HISTCONTROL=erasedups
#Java文字コードをUTF-8へ
# export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

# デフォルトエディタをvimに変更
EDITOR=/usr/local/bin/vim
export EDITOR

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
