if [ -f ~/.bashrc ] ; then
. ~/.bashrc
fi

# nodebrewのpathを通す
if [[ -d ~/.nodebrew ]]; then
    export PATH=$HOME/.nodebrew/current/bin:$PATH
    nodebrew use default
fi

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
## init rbenv
eval "$(rbenv init -)"

# git settings 
source ~/.git-completion.bash
source ~/.git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=true

## ユーザー名のところを編集(gitリポジトリの状態を追加)
export PS1='\h:\W $(__git_ps1 "[\[\033[32m\]%s\[\033[0m\]]")\$ '

# pkg-configのパスを通す
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/X11/lib/pkgconfig

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
## export COCOS_CONSOLE_ROOT=
## export PATH=$COCOS_CONSOLE_ROOT:$PATH

## Add environment variable NDK_ROOT for cocos2d-x
export NDK_ROOT=/usr/local/opt/android-ndk
export PATH=$NDK_ROOT:$PATH

## Add environment variable ANDROID_SDK_ROOT for cocos2d-x
export ANDROID_SDK_ROOT=/usr/local/opt/android-sdk
export PATH=$ANDROID_SDK_ROOT:$PATH
export PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH

## Add environment variable ANT_ROOT for cocos2d-x
export ANT_ROOT=/usr/local/bin
export PATH=$ANT_ROOT:$PATH

# less settings
export LESS="-iMQRX"
