[ -f ~/.bashrc ] &&
  . ~/.bashrc

[ -f ~/.ansible_hosts ] &&
  export ANSIBLE_HOSTS=~/.ansible_hosts

# Java settings
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

# nodebrew settings
[ -d ~/.nodebrew ] &&
  export PATH=$HOME/.nodebrew/current/bin:$PATH &&
  nodebrew use default

# rbenv settings
[ -d ~/.rbenv ] &&
  export PATH="$HOME/.rbenv/bin:$PATH" &&
  eval "$(rbenv init -)"

# git settings 
if [ -f ~/.git-completion.bash -a -f ~/.git-prompt.sh ] ; then
  source ~/.git-completion.bash
  source ~/.git-prompt.sh
  GIT_PS1_SHOWDIRTYSTATE=true

  ## ユーザー名のところを編集(gitリポジトリの状態を追加)
  export PS1='\h:\W$(__git_ps1 "[\[\033[32m\]%s\[\033[0m\]]") \$ '
fi

# pkg-configのパスを通す
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/X11/lib/pkgconfig
 
# Android SDK settings
if [ -d $HOME/Library/Android/sdk ]; then
  export ANDROID_HOME=$HOME/Library/Android/sdk
  export PATH=$ANDROID_HOME:$PATH
  export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
fi

# Android NDK settings 
if [ -d /usr/local/opt/android-ndk ]; then
  export ANDROID_NDK_ROOT=/usr/local/opt/android-ndk
  export PATH=$ANDROID_NDK_ROOT:$PATH
fi

# cocos2d-x settings
## export COCOS_CONSOLE_ROOT=
## export PATH=$COCOS_CONSOLE_ROOT:$PATH
# Ant settings(for cocos2d-x)
## export ANT_ROOT=/usr/local/bin
## export PATH=$ANT_ROOT:$PATH

# Heroku Toolbelt settings
[ -d /usr/local/heroku ] &&
  export PATH="/usr/local/heroku/bin:$PATH"

# less settings
export LESS="-iMQRX"

# history settings
export HISTCONTROL=erasedups

# editor settings
EDITOR=/usr/local/bin/vim
export EDITOR

# BasicTex settings
[ -d /usr/texbin ] &&
  export PATH=$PATH:/usr/texbin
