---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    homebrew_packages_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/versions
    homebrew_packages:
      - { name: rbenv }
      - { name: ruby-build }
      - { name: vim }
      - { name: tig }
      - { name: nkf }
      - { name: heroku-toolbelt }
      - { name: ag }
      - { name: hub }
      - { name: postgresql }
      - { name: jruby }
    homebrew_cask_packages:
      - atom
      - google-japanese-ime
      - google-chrome
      - dropbox
      - karabiner
      - bettertouchtool
      - karabiner
      - totalterminal
      - slack
      - kindle
      - evernote
      - java7
      - android-studio
      - android-file-transfer
      - genymotion
      - virtualbox
      - kobito
      - firefox
      - silverlight
    atom_packages:
      - vim-mode
      - japanese-wrap
      - emmet
  roles:
    - hnakamur.homebrew-packages
    - hnakamur.homebrew-cask-packages
    - hnakamur.atom-packages

  tasks:
    - name: mkdir vim-neobundle dir
      file: path=~/.vim/bundle state=directory
    - name: git clone neobundle
      command: git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
      notify: install neobundle

  handlers:
    - name: install neobundle
      command: ~/.vim/bundle/neobundle.vim/bin/neoinstall
